# Generated by Django 6.0.5 on 2026-05-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.PositiveIntegerField()),
                ('agent_name', models.CharField(blank=True, max_length=155, null=True)),
                ('agent_activation_date', models.CharField(blank=True, editable=False, max_length=50, null=True)),
            ],
        ),
    ]
