# Generated by Django 6.0.5 on 2026-05-26 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_delete_agent'),
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_commission_lifetime', models.PositiveIntegerField(blank=True, null=True)),
                ('total_commission_today', models.PositiveIntegerField(blank=True, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.agent')),
            ],
        ),
    ]
