# Generated by Django 6.0.5 on 2026-05-27 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
        ('entities', '0003_rename_agent_id_agent_agent_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='entities.agent', to_field='agent_cid'),
        ),
    ]
