# Generated by Django 6.0.5 on 2026-05-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agent_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
