# Generated by Django 6.0.5 on 2026-05-27 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_alter_agent_agent_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='agent_id',
            new_name='agent_cid',
        ),
    ]
